-keep class dagger.hilt.android.internal.managers.** { *; }
-keep class com.google.firebase.** { *; }
-keep class kotlinx.serialization.** { *; }
-keep class androidx.work.impl.WorkManagerInitializer
-keep class com.comunidadedevspace.imc.** { *; }
-dontwarn kotlinx.serialization.**
